services:
  rankeverything:
    image: woukie/rankeverything:latest
    environment:
      DB_HOST: "127.0.0.1"
      DB_NAME: "database"
      DB_USER: "user"
      DB_PASSWORD: "password"
    ports:
      - 8080:80
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
